[package]
name = "miohttp"
version = "0.1.0"
authors = ["szagi3891 <szeligagrzegorz@gmail.com>", "sfisol <sfisol@gmail.com>"]

[dependencies]
#mio = "0.5.0"
httparse = "1.1.0"
net2 = "0.2"
libc = "0.1"


[dependencies.mio]
git = "https://github.com/carllerche/mio"
